services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8000"
